### PR TITLE
additional options for mux plugin

### PR DESCRIPTION
**Pull request by haraldjordan78**
Dear Thierry,

sorry again for the extra-effort. I did not wish to commit 2 changes in one pull request of course but it seems thats the way how github works. Still learning though.

The following changes to the mux plugin introduce multiple additional options that let the user specify a PCR time where to start and end insertion, as well as a repetition time, e.g. insert a packet only every x milliseconds. 

Again of course in very basic coding style, i hope you still like the changes and do not have to invest too much effor to make it fulfill your standards. 

The new code is of course tested and also i tested some old functions (sure not all), and to work as designed.

The most problematic spot in my humble opinion is line 355, where i enclose your original "read from file into packet" code in my if statement. 
Second problematic is the use of a signal _minmaxpts_rangeOK which makes reading and writing additional functions pretty hard. But unfortunately i could not imagine a much better way besides probably creating a whole new plugin.
Third problematic is the new option --minmaxptspid: it's name might be wrong as  i am expecting a pcr pid actually. Probably this should be named pcrpid and additionally the code should check if this option is needed and error in case it is not defined.

Please let me know your thoughts and i am happy to re-engineer.

Greetings from Vienna!

### CODE REVIEW

**Comment by lelegard** [comment]
Hi Harald,

Thank you for your pull request. It looks really nice and I will review and integrate it. Probably not today though.

Concerning the 2 fixes in 1 PR, do not worry. The PR workflow (and even git in general) is not straightforward at the beginning. One thing to remember, as highlighted in the [article](https://gist.github.com/Chaser324/ce0505fbed06b947d962) I previously mentioned, is to create a distinct branch per new feature (future PR), in your forked repository. Thus, the 2 features can be pushed and merged independently.

Cheers from Paris !

**Comment by lelegard** [comment]
And injecting data based on PTS values is a perfume of SCTE 35 ... :)

**Comment by haraldjordan78** [comment]
Hehe "a perfurme of SCTE 35" is well expressed. Possibly it is worth to introduce a new plugin for SCTE insertion but as the mux plugin does not have too many options, my additions would fit into it. Whenever you have the time to review, please just let me know any doubt.

**Comment by lelegard** [comment]
Hi Harald,

I am currently integrating your code. I understand that you use PTS = PCR / 300. But, formally, splicing cues are based on PTS values from the PES headers, not PCR in TS AF. In practice, it is true that PTS and PCR's are fully synchronised, but not always in the same PID. Sometimes, the PCR PID of a service is on its own, carrying nothing else than PCR's. So, in case the user specifies by mistake the video PID of the service instead of the PCR PID, if the two PID's are different, this won't work. I will make the following change: when collecting time stamps from packets, I take the one I find, PCR (/300) or PTS, whichever is present. What do you think?

**Comment by lelegard** [comment]
Hi Harald,

I have merged your PR. I have made a few modifications:

- Renamed options for consistency with others: `--inter-time`, `--max-insert-count`, `--min-pts`, `--max-pts` and `--pts-pid`
- I fixed a logic error near the end. It would not work when the input file contains packets from distinct PID's.
- I removed your processing of the CC, this was already done.

Could you please validate if the modified version passes your tests ? I will wait for your answer before releasing version 3.10, just in case I introduced a bug.

Thank you Harald for your work.

**Comment by haraldjordan78** [comment]
Hi Thierry,

you are too kind. Thanks a lot for all the time you invest to this. I checked in detail the differences between my original modifications and your enhancement. Sure everything looks ok for me. 

It is a smart idea of you to just default to the last PCR in case the --pts-pid option is 0. Sure this only works for SPTS but i guess most tsduck users deal with SPTS instead of MPTS and the ones who do have a MPTS need to be aware of their PCR PID anyway. 

Please give me a week to confirm the new version is working as designed but from the code i could not see any doubt about that. 

Spending about an hour to diff your changes (wanted to be sure i got everything) was cosmetical enhancements:
move line 351 to  307
move line 385 to 366 

The thing i liked most was your change to my #1 problematic spot i mentioned originally. I was aware that this is a problematic spot but i could not imagine to do negative tests instead of positive tests. But in the end your check makes everything more clear and readable, even if negative tests are generally teached as taboo.

OLD:
if (_minmaxpts_rangeOK && (_max_insert_count > _inserted_packet_count || _max_insert_count == 0)) {

NEW: 
if (!_pts_range_ok || (_max_insert_count != 0 && _inserted_packet_count >= _max_insert_count)) {

I regret that you did have to invest that much time for my changes and feel pleased that you did. It teaches me great lessons!
Please give me a week to confirm the new code works in production. If you like, i can update the word documentation as soon as everything is released.

All the Best,
Harald

**Comment by lelegard** [comment]
>  i guess most tsduck users deal with SPTS instead of MPTS 

Certainly not. I have used TSDuck for years mostly on MPTS. Each time you get a stream from a DVB tuner, satellite, terrestrial, etc, this is an MPTS. I hardly used SPTS outside IP-TV. So, being prepared for all kinds of TS is essential.

**Pull request merged**
