### PR TITLE
Add bskyb_logical_number descriptor

### PR DESCRIPTION
**Pull request by spnngl**
This descriptor has tag 0xB1 and follow a BskyB private_data_specifier.

I'm currently searching the structure of the 0xB2 (aka bskyb_service_descriptor) on the net but cannot find anything useful apart from a "category byte". If someone has informations about it I am willing to integrate it to TSDuck...

Anthony Delannoy

### CODE REVIEW

**Comment by lelegard** [comment]
Hi @spnngl,

Thank you for your contribution. The signalisation is so vast that help from contributors is more than welcome. I will merge it in the next few days. In the meantime, could you please:

- Replace my name with yours in the copyrights of the new source files you created (you wrote the code, I didn't).
- Add the definition of `< sky_logical_channel_number_descriptor>` in the file `tsduck.tables.model.xml`. Without templates, your descriptor will not compile. See an example [here](https://github.com/tsduck/tsduck/blob/master/src/libtsduck/tsduck.tables.model.xml#L1288).

**Comment by spnngl** [comment]
Okay, will do today if I have time.
Thanks for the quick response !

**Comment by lelegard** [comment]
About the 0xB2 descriptor, you may have a look at this:
https://github.com/Duckbox-Developers/dvbsnoop/blob/master/src/private/bskyb.uk/dvb_descriptor_bskyb.c

But this is open source code, not a BskyB reference. The code mentions a doc named " BskyB-Unified ver 1.0, 24.12.2016". Any idea where to find it? Probably not a public document.

@spnngl, do you have a captured BskyB stream you can share?

**Comment by spnngl** [comment]
I will push the final version of 0xB1 before 16h.

Yes I saw that reference for 0xB2, it was the only useful. I did not find this BskyB document even by scanning their site for PDFs...

I will continue to look for a complete reference.

**Comment by lelegard** [comment]
> Edit: I work directly on a parabola (sat 28.2 freq 11,611,750,000). Do you want an extract?

It would be great to have a 60 seconds TS capture of one or two main BskyB transponders.

If you agree, we can push them on the [TSDuck stream repository](https://tsduck.io/streams/).

As far as I am concerned, I have access to Astra 19.2E, HotBird13E, Atlantic Bird 5W and DVB-T over Paris area.

**Comment by spnngl** [comment]
Okay I will record them.

I have access to 19.2E, 28.2E, 13E and 23.5E for now and can have access on some west (but I do not know which ones) plus DVB-T on Paris too.

**Comment by lelegard** [comment]
Hi @spnngl 

I have integrated your contribution. Thanks again!

I have added test suite 055 for BskyB private descriptors in the [TSDuck tests](https://github.com/tsduck/tsduck-test). This has exhibited a bug in the XML deserialization that I fixed. This is obviously a very common copy/paste bug.
~~~
-    children[i]->getIntAttribute<uint16_t>(entry.channel_id, u"sky_id", true, 0, 0x0000, 0xFFFF);
+    children[i]->getIntAttribute<uint16_t>(entry.sky_id, u"sky_id", true, 0, 0x0000, 0xFFFF);
~~~
This demonstrates the utility of a good non-regression test suite.

If you implement more BskyB private descriptors, a sample will be added in the same test suite.

**Comment by lelegard** [comment]
And if you have the opportunity to capture a few BskyB transponders, please contact me at contact@tsduck.io.

**Comment by spnngl** [comment]
Great news thanks :)

I may have found something for the 0xB2 bskyb descriptor. I'll try to finalize this next week and do the tests this time ^^

I'll contact you next week for the bskyb capture too.

**Pull request merged**
