### PR TITLE
TSAnalyze: Aggregated bitrate of 0x00-0x1F pids

### PR DESCRIPTION
**Pull request by lars18th**
This patch adds one line with the subtotal of PSI data in the section SERVICES ANALYSIS REPORT.

Example:

```
===============================================================================
|  SERVICES ANALYSIS REPORT                                                   |
|=============================================================================|
|  Global PID's                                                               |
|  TS packets: 6,427,621, PID's: 8 (clear: 8, scrambled: 0)                   |
|-----------------------------------------------------------------------------|
|     PID  Usage                                     Access          Bitrate  |
|   Total  Global PID's ................................. C   15,428,731 b/s  |
|  0x0000  PAT .......................................... C        3,168 b/s  |
|  0x0001  CAT .......................................... C        3,168 b/s  |
|  0x0010  DVB-NIT ...................................... C          151 b/s  |
|  0x0011  SDT/BAT ...................................... C          760 b/s  |
|  0x0012  EIT .......................................... C       70,170 b/s  |
|  0x0014  TDT/TOT ...................................... C          100 b/s  |
|  0x0015  Network Synchronization ...................... C        2,467 b/s  |
|  0x1FFF  Stuffing ..................................... C   15,348,744 b/s  |
|   Total  PSI data (without NULLs) ..................... C       79,984 b/s  |
|=============================================================================|
```

### CODE REVIEW

**Comment by lelegard** [comment]
Hi, @lars18th,

Thanks for your contribution. I see that you are coming to programming now, good !

I have one remark: The global PID's sections contains all PID's which are not attached to any specific service. In the general case, this includes the EMM PID's, the total bitrate of which is often much higher than the global PSI. I think they should be included in this total.

Which makes the name "PSI data" not completely appropriate. In fact, PSI includes PMT's which are not accounted here. And SDT, BAT, EIT, TOT, TDT are SI, not PSI. So, the name should probably be something like "Global PID's (stuffing excluded)". OK, I clearly admit that this is rather pedantic, sorry 😉

**Comment by lars18th** [comment]
Hi @lelegard ,

So what is your suggestion then?

- Change the label to "Global PID's (stuffing excluded)", or
- Include **all** PSI/SI stuff plus the PMT's, and use the label "Global PSI/SI (without NULL stuff)".

Please, comment to change it, and close the PR.
Regargs.

**Comment by lelegard** [comment]
~~~
|     PID  Usage                                     Access          Bitrate  |
|   Total  Global PID's ................................. C   15,428,731 b/s  |
....
|  0x1FFF  Stuffing ..................................... C   15,348,744 b/s  |
|   Total  PSI data (without NULLs) ..................... C       79,984 b/s  |
~~~
Thinking twice, I have a few more objections:
- In all other sections, the total is on first line, not last one. So, this is a bit confusing.
- The bitrate of global PID's (including stuffing) is already on the first line, the information on the last line does not bring much information (except subtracting the stuffing bitrate).
- The computation of the global bitrate in the last line is not accurate because it is a sum of final bitrates, adding up all imprecisions of the divisions. The total bitrate on the first line is computed from the sum of packets, not a sum of bitrates, giving a more precise result. The strange result is that, in the absence of stuffing in the TS, the bitrate in the final line is different from the one in the first line, while they describe exactly the same amount of packets. Believe me, I tried before integrating the PR.

Sorry if this is a bit harsh to say, but we should probably simply drop the modification.

**Comment by lars18th** [comment]
Hi @lelegard ,

I'm going to try to argue the patch:

> In all other sections, the total is on first line, not last one. So, this is a bit confusing.

Not really, as _after_ the NULL list is the subtotal. Perhaps if I change "Total" with "Subtotal" it will be more clear. You agree?

> The bitrate of global PID's (including stuffing) is already on the first line, the information on the last line does not bring much information (except subtracting the stuffing bitrate).

Yes, and if a human needs to read the output, the subtraction of the stuffing bitrate is a **valuable data**. Please, think on which data has sense: the "total bitrate" of a TS; the "bitrate" of each pid; the "bitrate" of a servicio... But, where is the total bitrate of the "valid data"? And where is the bitrate of the "complementary data" (valid data minus the service data; that's the PSI/SI tables)?

> The computation of the global bitrate in the last line is not accurate because it is a sum of final bitrates, adding up all imprecisions of the divisions. The total bitrate on the first line is computed from the sum of packets, not a sum of bitrates, giving a more precise result. The strange result is that, in the absence of stuffing in the TS, the bitrate in the final line is different from the one in the first line, while they describe exactly the same amount of packets. Believe me, I tried before integrating the PR.

OK, so see this new suggestion:
```
===============================================================================
|  SERVICES ANALYSIS REPORT                                                   |
|=============================================================================|
|  Global PID's                                                               |
|  TS packets: 6,427,621, PID's: 8 (clear: 8, scrambled: 0)                   |
|-----------------------------------------------------------------------------|
|     PID  Usage                                     Access          Bitrate  |
|   Total  Global PID's ................................. C   15,428,731 b/s  |
....
|  0x1FFF  Stuffing ..................................... C   15,348,744 b/s  |
| Subtotal PSI/SI data only (pids 0-31) ................. C       79,984 b/s  |
|=============================================================================|
```

The problem is that I really need the subtotal (partial sum) of all PSI/SI packets. And the current output doesn't print this data.

Any new idea?

**Comment by lars18th** [comment]
Hi @lelegard ,

After thinking more about _simplicity_, I think I've found a good solution.
See this new proposal:

```
===============================================================================
|  SERVICES ANALYSIS REPORT                                                   |
|=============================================================================|
|  Global PID's                                                               |
|  TS packets: 6,427,621, PID's: 8 (clear: 8, scrambled: 0)                   |
|-----------------------------------------------------------------------------|
|     PID  Usage                                     Access          Bitrate  |
|   Total  Global PID's ................................. C   15,428,731 b/s  |
|  0x0000  PAT .......................................... C        3,168 b/s  |
|  0x0001  CAT .......................................... C        3,168 b/s  |
|  0x0010  DVB-NIT ...................................... C          151 b/s  |
|  0x0011  SDT/BAT ...................................... C          760 b/s  |
|  0x0012  EIT .......................................... C       70,170 b/s  |
|  0x0014  TDT/TOT ...................................... C          100 b/s  |
|  0x0015  Network Synchronization ...................... C        2,467 b/s  |
|  0x1FFF  Stuffing ..................................... C   15,348,744 b/s  |
|          Aggregated bitrate of PIDs: 0x00-0x1F ........ C       79,984 b/s  |
|=============================================================================|
```

I feel this info is clear and not intrusive.
I hope you agree, and merge this PR.

Regards.

**Comment by lars18th** [comment]
Hi @lelegard ,

After thinking more about _simplicity_, I think I've found a good solution.
See this new proposal:

```
===============================================================================
|  SERVICES ANALYSIS REPORT                                                   |
|=============================================================================|
|  Global PID's                                                               |
|  TS packets: 6,427,621, PID's: 8 (clear: 8, scrambled: 0)                   |
|-----------------------------------------------------------------------------|
|     PID  Usage                                     Access          Bitrate  |
|   Total  Global PID's ................................. C   15,428,731 b/s  |
|  0x0000  PAT .......................................... C        3,168 b/s  |
|  0x0001  CAT .......................................... C        3,168 b/s  |
|  0x0010  DVB-NIT ...................................... C          151 b/s  |
|  0x0011  SDT/BAT ...................................... C          760 b/s  |
|  0x0012  EIT .......................................... C       70,170 b/s  |
|  0x0014  TDT/TOT ...................................... C          100 b/s  |
|  0x0015  Network Synchronization ...................... C        2,467 b/s  |
|  0x1FFF  Stuffing ..................................... C   15,348,744 b/s  |
|          Aggregated bitrate of PIDs: 0x00-0x1F ........ C       79,984 b/s  |
|=============================================================================|
```

I feel this info is clear and not intrusive.
I hope you agree, and merge this PR.

Regards.

**Comment by lelegard** [comment]
Hi @lars18th,

I integrated your contribution. I usually prefer to credit all contributors, no matter the size of the contribution (see file CONTRIBUTORS.txt). There is no obligation (no NSA here!) but I prefer to. If you'd like to be listed here, please send me your full name.

As I mentioned in a previous comment, I had to slightly modify the bitrate computation. Simply adding the bitrates of the components added the imprecisions and in TS without EMM's and without stuffing, the two lines about global PID's and PID's below 0x1F were different by a few bits. I also moved your summary up because it was a bit misplaced far away after all EMM PID's (seen on TS with a lot of EMM's).

Finally, outside your contributed code, I took this opportunity to do some cleanup on the top part with `--wide-display` which was a bit ugly previously.

Thanks.

**Pull request merged**
