### PR TITLE
Improve PTS management in Sync PES Encapsulation

### PR DESCRIPTION
**Pull request by lars18th**
Improve the calculation of the PTS values when using the Synchronous PES Encapsulation.

### CODE REVIEW

**Comment by lars18th** [comment]
Hi @lelegard ,

Please merge this PR. Without it the PTS marks generated can be invalid in some cases. This code makes the calculation more robut, and now the FFmpeg encoder agree every time with the new marks.

Regards.

**Comment by lelegard** [comment]
Hi, 

It seems that the PR is incorrect because of some typical Git Black Magic. The commits contain all combined modifications in recent commits. In other words, the PR affects several dozens of files, which is certainly not your intention. I cannot merge it like that. You should reconsider it, rebase it from the repo and make sure the PR affects only the files you modified.

**Comment by lars18th** [comment]
OK @lelegard ,

I'll try to recreate it. I hate the "rebase" functionality implemented in GitHub. :unamused:

**Comment by lars18th** [comment]
Hi @lelegard ,

Please merge #302 . :wink:

**Pull request closed without merging**
