### PR TITLE
Atsc tuning fixes

### PR DESCRIPTION
**Pull request by oviano**
I can't test actual reception yet, but I've verified that my code looks up the frequency and gets the corresponding physical channel so I'm confident it will work from my tests last weekend when the laptop was in a reception area.

However, the "--hf-band-region" does not appear to work for the tsp command, so it mapped frequency 207000000 to channel 9 which would I think be the VHF channel for Europe.

### CODE REVIEW

**Comment by lelegard** [comment]
Hi,

I will integrate this one.

> However, the "--hf-band-region" does not appear to work for the tsp command, so it mapped frequency 207000000 to channel 9 which would I think be the VHF channel for Europe

I do not see this. It seems to work for me. UHF example:
~~~
$ tsp -v -I dvb --uhf 30 --hf-band-region europe -O drop
* dvb: using PCTV 291e/461e BDA 28179 TVTuner (DVB-T)
* dvb: tuned to transponder --frequency 546,000,000 ...
$
$ tsp -v -I dvb --uhf 30 --hf-band-region usa -O drop
* dvb: using PCTV 291e/461e BDA 28179 TVTuner (DVB-T)
* dvb: tuned to transponder --frequency 569,000,000 ...
$ 
~~~
VHF example:
~~~
$ tsp -v -I dvb --vhf 9 --hf-band-region europe -O drop
* dvb: using PCTV 291e/461e BDA 28179 TVTuner (DVB-T)
* dvb: tuned to transponder --frequency 205,500,000 ...
$
$ tsp -v -I dvb --vhf 9 --hf-band-region usa -O drop
* dvb: using PCTV 291e/461e BDA 28179 TVTuner (DVB-T)
* dvb: tuned to transponder --frequency 189,000,000 ...
~~~

**Comment by oviano** [comment]
Ok I will re-test, maybe I screwed something up with my command!

**Comment by lelegard** [comment]
Hi Oliver,

I just integrated your pull request. Please note that I appreciate your coding and the way you clearly respect the coding style of the project. I have only one remark: please take care of tab characters. Visual Studio uses 4-chars tabs while most editors and operating systems uses 8-chars tabs. This means that a code which is edited by Visual Studio with default settings appears with garbage indentation in other editors. This is why I have configured VS and all other IDE's to never insert tabs, always spaces. In all environments, a space is just a space...

**Comment by oviano** [comment]
No problem at all - I’m aware of it, and thought I’d caught all of them as I committed but I must have missed a few.

**Pull request merged**
