### PR TITLE
Implementation of AIT

### PR DESCRIPTION
**Pull request by ElyKar**
This is the proposed implementation of AIT, as discussed in #33 .

### CODE REVIEW

**Comment by lelegard** [comment]
Hello Tristan,

Thanks for the work. I just had a quick look at the code. It looks good. Nice work.

I will not be able to look at it more closely and merge it before the end of next week (I won't bring any computer during my vacations...) But I will definitely do it, just be patient.

Just one small point. I would prefer you keep the same exact coding style and presentation as the rest of the project. I do not criticize your coding style. There are some bad - or even very bad - coding styles and many different good coding styles. Your style is a good one. But inside a given project, there is only one recommended style, the same consistent one as the rest of the project.

PS: I pushed a couple of commits last night that you may want to merge. I promise not to push any other in the next 10 days for the aforementioned reason.

Thanks

**Comment by ElyKar** [comment]
Sure take your time, there is no rush.
About the coding style, thanks for pointing that out, I should have taken more care of it. In fact, I let my editor (vim) take care of autoformatting everything and didn't look further. I will change that to match the rest of the project while merging the most recent changes.

**Comment by lelegard** [comment]
Integrated, thanks for your work.
Feel free to add more contributions regarding HbbTV signalling.

**Comment by lelegard** [comment]
Hi @ElyKar 

I see something strange in the dump of the AIT from the test stream (which is a real world stream from Eutelsat 13°E).
~~~
* AIT, TID 116 (0x74), PID 7877 (0x1EC5)
  Version: 0, sections: 1, total size: 182 bytes
  - Section 0:
    Application type: 1 (0x0001), Test application: 0
    Application: Identifier: (Organization id: 11 (0x0000000B), Application id: 6837 (0x1AB5)), Control code: 2
    - Descriptor 0: AIT Application (0x00, 0), 9 bytes
      0000:  05 00 01 01 01 01 3F 3C 01                 ......?<.
    - Descriptor 1: AIT Application Name (0x01, 1), 23 bytes
      0000:  69 74 61 13 50 72 6F 67 72 61 6D 6D 69 20  ita.Programmi
      000E:  54 56 20 42 42 20 53 41 54                 TV BB SAT
    - Descriptor 2: Hierarchy (0x04, 4), 43 bytes
      0000:  01 2F 00 69 74 2E 6D 65 64 69 61 73 65 74  ./.it.mediaset
      000E:  2E 73 63 68 65 64 75 6C 65 73 74 76 2E 50  .schedulestv.P
      001C:  6F 72 74 61 6C 65 4C 69 67 68 74 58 6C 65  ortaleLightXle
      002A:  74                                         t
    - Descriptor 3: Audio Stream (0x03, 3), 0 bytes
    - Descriptor 4: AIT Transport Protocol (0x02, 2), 72 bytes
      0000:  00 03 01 30 68 74 74 70 3A 2F 2F 6D 68 70  ...0http://mhp
      000E:  2E 64 67 74 76 2E 6D 65 64 69 61 73 65 74  .dgtv.mediaset
      001C:  2E 69 74 2F 61 70 70 6C 2F 50 72 6F 67 72  .it/appl/Progr
      002A:  61 6D 6D 69 54 76 53 61 74 2F 01 12 50 72  ammiTvSat/..Pr
      0038:  6F 67 72 61 6D 6D 69 54 76 53 61 74 2E 7A  ogrammiTvSat.z
      0046:  69 70                                      ip
~~~

All descriptors have tags below 0x3F, the overlapping range between ISO 13818-1 (MPEG-TS) and ETSI TS 102 809 (HbbTV signalling). Since we are in an AIT, the HbbTV values prevail. We can see that descriptor tags 0x00, 0x01 and 0x02 are correctly recognized as AIT-specific. However, descriptor tags 0x03 and 0x04 are also present and these values are not defined in ETSI TS 102 809. Looking at descriptor number 2, tag 0x04, it is obvious that this is an HbbTV information and not an MPEG-defined hierarchy descriptor. Similarly, it seems doubtful that descriptor number 3 is an MPEG-defined audio descriptor.

Do you have any idea where these two obviously AIT-specific descriptor tags 0x03 and 0x04 come from? My copy of ETSI TS 102 809 is the latest one, v 1.3.1 from June 2017, and they are not documented there.

**Comment by ElyKar** [comment]
Hi, I suspect these descriptors are defined in DVB-MHP specification. Here is the table layout according to dvbsnoop :
```
$ dvbsnoop -s ts -N 3 -tssubdecode -if test-018.ts 0x1ec5
    ....
    TS sub-decoding (1 packet(s) stored for PID 0x1ec5):
    =====================================================
    TS contains Section...
    SI packet (length=182): 
        PID:  7877 (0x1ec5)

        Guess table from table id...
        AIT-decoding....
        Table_ID: 116 (0x74)  [= MHP- Application Information Table (AIT)]
        Section_syntax_indicator: 1 (0x01)
        reserved_1: 1 (0x01)
        reserved_2: 3 (0x03)
        section_length: 179 (0x00b3)
        test_application_flag: 0 (0x00)
        application_type: 1 (0x0001)  [= DVB-J application]
        reserved_3: 3 (0x03)
        Version_number: 0 (0x00)
        Current_next_indicator: 1 (0x01)  [= valid now]
        Section_number: 0 (0x00)
        Last_section_number: 0 (0x00)
        reserved_4: 15 (0x0f)
        common_descriptors_length: 0 (0x0000)

        reserved_5: 15 (0x0f)
        application_loop_length: 166 (0x00a6)
            organisation_id: 11 (0x0000000b)
            appliction_id: 6837 (0x1ab5)  [= unsigned applications]
            application_control_code: 2 (0x02)  [= PRESENT]
            reserved: 15 (0x0f)
            application_descriptor_loop_length: 157 (0x009d)

               MHP_AIT-DescriptorTag: 0 (0x00)  [= Application descriptor]
               descriptor_length: 9 (0x09)
               application_profile_length: 5 (0x05)

                  application_profile: 1 (0x0001)
                  version.major: 1 (0x01)
                  version.minor: 1 (0x01)
                  version.micro: 1 (0x01)

               service_bound_flag: 0 (0x00)
               visibility: 1 (0x01)  [= application not visible to user, but visible to appl. listening api]
               reserved: 31 (0x1f)
               application_priority: 60 (0x3c)
               transport_protocol_label: 1 (0x01)

               MHP_AIT-DescriptorTag: 1 (0x01)  [= Application name descriptor]
               descriptor_length: 23 (0x17)
                  ISO639_language_code:  ita
                  application_name_length: 19 (0x13)
                  application_name: "Programmi TV BB SAT"  -- Charset: Latin alphabet


               MHP_AIT-DescriptorTag: 4 (0x04)  [= DVB-J application location descriptor]
               descriptor_length: 43 (0x2b)
               base_directory_length: 1 (0x01)
               base_directory: "/"
               classpath_extension_length: 0 (0x00)
               classpath_extension: ""
               initial_class: "it.mediaset.schedulestv.PortaleLightXlet"

               MHP_AIT-DescriptorTag: 3 (0x03)  [= DVB-J application descriptor]
               descriptor_length: 0 (0x00)

               MHP_AIT-DescriptorTag: 2 (0x02)  [= Transport protocol descriptor]
               descriptor_length: 72 (0x48)
               protocol_id: 3 (0x0003)  [= Transport via HTTP over the interaction channel]
               transport_protocol_label: 1 (0x01)

               URL_base_length: 48 (0x30)
               URL_base: "http://mhp.dgtv.mediaset.it/appl/ProgrammiTvSat/"

               URL_extension_length: 1 (0x01)
               URL_extension: "."

               URL_extension_length: 80 (0x50)
               URL_extension: "rogrammiTvSat.zip...x..........................................................."

    CRC: 2912884600 (0xad9f1778)
```
The last descriptor is not decoded correctly, however given that the application transmitted is a Java app, it seems plausible to me that this stream uses the MHP spec and not TS 102 809 (To be honest, I don't really understand what they did with the AIT and descriptors, because it's been defined years ago for MHP and they moved it to a new spec after that).

**Comment by lelegard** [comment]
You are right, they are defined in ETSI TS 101 812. I will add the corresponding definitions.

**Comment by lelegard** [comment]
@ElyKar 

Here is a summary of AIT / HbbTV availability on the French TNT. The UHF channels are valid for the Paris - Tour Eiffel transmitter. I can provide captures if you need some.

~~~
LCN   Channel     TS    UHF   AIT PID   HbbTV carousel PID
---   ---------   ---   ---   -------   ------------------
1     TF1         R6    32    0x00AA   n/a
4     Canal+      R3    22    0x03B7   n/a
6     M6          R4    30    0x00AA   0x00AB (100 kb/s)
7     Arte        R4    30    0x0172   0x0173 (20 kb/s)
8     C8          R2    25    0x00AA   n/a
12    NRJ12       R6    32    0x010E   0x010F (50 kb/s)
13    LCP         R6    32    0x0302   n/a
16    CNEWS       R2    25    0x01D6   n/a
17    CSTAR       R2    25    0x023A   n/a
18    Gulli       R2    25    0x029E   0x029F (50 kb/s)
25    Chérie 25   R10   42    0x0172   0x0173 (50 kb/s)

~~~

**Pull request merged**
