### PR TITLE
Add new "retime" plugin to change PTS/DTS values

### PR DESCRIPTION
**Pull request by lars18th**
With this new plugin it's possible to modify the PTS/DTS values.

### CODE REVIEW

**Comment by lars18th** [comment]
Hi @lelegard ,

I hope you agree with this new plugin.
However, I need your help to manage the time back in the counters. Any idea?

Regards.

**Comment by lelegard** [comment]
Two questions:

Is it on purpose that the PCR are not modified? Normally, the PTS and DTS values are based on the PCR reference clock of the service. Modifying the PTS and DTS without modifying the PCR can make the stream unplayable.

Wouldn't it be better to implement this as an enhancement of  `pcradjust` ?

**Comment by lars18th** [comment]
> Two questions:

Hi,

> Is it on purpose that the PCR are not modified? Normally, the PTS and DTS values are based on the PCR reference clock of the service. Modifying the PTS and DTS without modifying the PCR can make the stream unplayable.

No. Modifying the PTS and DTS values are for sub-stream synchronization. One example: you want to add a new data stream to a current service muxing it from an external source. And this data stream requires to be in synch with the rest of the sub-streams in the service. Then you can use this plugin to achieve this objective: after muxing it you can calculate the offset and apply it.

> Wouldn't it be better to implement this as an enhancement of `pcradjust` ?

You're the developer of the TSDuck, and I take your opinion very seriously. However, for this particular case I suggest to not merge it.

Regards.

**Comment by lelegard** [comment]
OK, that makes sense. The plugin `pcradjust` makes a global and automated modification while `retime` fixes a specify issue that was manually detected on individual PID's.

To comply with the usual policy in open source projects, please update the copyright header with your full name. I cannot claim copyright for a file I did not write.

**Comment by lars18th** [comment]
> To comply with the usual policy in open source projects, please update the copyright header with your full name. I cannot claim copyright for a file I did not write.

Done (partially)! A lot of code is copy-and-paste from **your** code, so you need to appear on it. Futhermore, I'm sure you'll continue contributing to it. :laughing: 

Regards.

**Comment by lelegard** [comment]
Please use your real name, TSDuck is an open and transparent project, see [CONTRIBUTORS.txt](https://github.com/tsduck/tsduck/blob/master/CONTRIBUTORS.txt).

**Comment by lars18th** [comment]
Hi @lelegard ,

I do a small makeup change in the debug message. Please, merge this new plugin. I'm using it a lot in my processing. And it works with both: positive and negative offsets without troubles.

Thank you!

**Comment by lelegard** [comment]
Hi @lars18th,

I have seen that you added the confused emoji to my request to provide your real name as contributor.

Let me clarify my position. The world of TV is roughly divided in industries, service providers, TV operators and pirates. I have worked in the first three categories and I have always fought against the fourth one. A toolbox such as TSDuck is useful to everyone, equally. I cannot prevent pirates to use TSDuck to build their infrastructure. And I know that some of them do. But it must be clear to everyone that TSDuck is made by engineers for engineers. I want TSDuck to be a fully transparent project: open source, identified web sites, _identified authors and contributors_.

In the world of Pay-TV, anonymity equals piracy. This may seem unfair but this is the way it is perceived by the industry. So, to maintain the trust in TSDuck, I keep anonymity away from it.

For small bug fixes, I can accept anonymous PR's because they are safe to validate. But when it comes to major contributions such as new plugins and their subsequent evolution, I need to keep a strict public policy.

I am sorry if you disagree, but this is a very sensitive topic in the TV industry.

**Comment by lars18th** [comment]
Hi @lelegard,

I'm back from vacation these days. That's why it's been a long time since I've made any comments.

As for your position, I now understand your reasons. And I accept it. However, although I’m an engineer, I cannot mix my work with other projects. And for that reason I can only use an alias in Github. So in my case it’s impossible to meet your requirements. I hope you can at least understand my position. And if for any reason you think that my comments or collaborations with this project may be harmful, please tell me, as I wouldn't want to interfere with this great project.

I hope someday I can still meet you in person.
Regards.

**Comment by lelegard** [comment]
> However, although I’m an engineer, I cannot mix my work with other projects. And for that reason I can only use an alias in Github.

Well, all contributors in TSDuck are engineers. I am a full time employee of my company. I work at home on TSDuck and I work at the office for my company. The days where TSDuck was useful to me everyday at work are unfortunately gone (although some of my colleagues still find it useful). Unless you work for some secret service, you are free to work on personal projects from home.

> I hope someday I can still meet you in person.

I will spend one day at IBC, for what it's worth...

**Comment by lars18th** [comment]
Hi @lelegard ,

> > However, although I’m an engineer, I cannot mix my work with other projects. And for that reason I can only use an alias in Github.
> 
> Well, all contributors in TSDuck are engineers. I am a full time employee of my company. I work at home on TSDuck and I work at the office for my company. The days where TSDuck was useful to me everyday at work are unfortunately gone (although some of my colleagues still find it useful). Unless you work for some secret service, you are free to work on personal projects from home.

It seems to me that you haven't understood the reason. For sure, I'm not involved in any secret service or piracy company. But the truth is, I can't do what you're asking.

> > I hope someday I can still meet you in person.
> 
> I will spend one day at IBC, for what it's worth...

I can't attend it this year. Sorry!

I will try to continue collaborating with this project if you don't mind. Please let me know if at any time my participation is a problem. I don't want to interfere with this useful project.

Regads.

**Comment by lars18th** [comment]
Hi @lelegard ,

I updated the plugin with the inclusion of the Visual files required to compile it for Windows. And I changed the attribution to Public Domain. So I don't need at all that you include my name (or nick) in the source code. And publishing it as Public Domain, I hope you can include it.

Regards.

**Comment by lelegard** [comment]
> I changed the attribution to Public Domain. So I don't need at all that you include my name

The license (public domain or whatever) and the contributor identity / anonymity are two independent data. I have published the [transparency rule in the contributions guidelines](https://tsduck.io/doxy/contributing.html). Originally, I did not imagine it was a problem for any developer to identify himself and I thought this rule was implicit. Now, it has become explicit.

And BTW, your source is not anonymous, it mentions _my_ name. This is impersonation.

**Comment by lars18th** [comment]
Hi @lelegard ,

I'm just looking for a comfortable solution for both of us.

> And BTW, your source is not anonymous, it mentions my name. This is impersonation.

That's not my objective. The skeleton of the source is _your_ code, and it uses _your_ header. So I'm only adding this line `// Plugin developed as Public Domain.` to distribute my contribution as Public Domain.

I'm sorry if my (required) position does not meet your requirements. I only want to contribute. Please take note that:

1. I could use a pseudonym (fake name), but that would be hoaxing and I don't want to dirty your excellent work.
2. I honestly tell you that I don't work for any company that works on piracy (you can believe me or not).
3. I hope someday we can get to know each other. My problem is not that you can meet me personally (which I would like to be able to meet you, on the other hand).

So tell me what I can do to meet your rules.
Regards.

**Comment by lelegard** [comment]
Closing this one (too old and not compliant with the [contribution policy](https://tsduck.io/doxy/contributing.html#transparency))

**Comment by lars18th** [comment]
Hi @lelegard ,

> Closing this one (too old and not compliant with the [contribution policy](https://tsduck.io/doxy/contributing.html#transparency))

I understand your position. No oposition to it.

Although perhaps you would like to implement an alternative by yourself. So you can provide a similar plugin to modify the PTS/DTS values, or enhance some already existent plugin for a similar functionality. One use case of such plugin is this: when you remux some services, if you want to merge/inject/transplant some pid from one service to another, then you need to _sync_ the clock of the moved substreams with the clock of the target service. Then in this case such functionality is useful.

What you think?

**Comment by lars18th** [comment]
Hi @lelegard ,

With all due respect, and with no intention of interrupting your great work, I would like to know your opinion about my previous comment. Please, could you say something?

> Although perhaps you would like to implement an alternative by yourself. So you can provide a similar plugin to modify the PTS/DTS values, or enhance some already existent plugin for a similar functionality. One use case of such plugin is this: when you remux some services, if you want to merge/inject/transplant some pid from one service to another, then you need to sync the clock of the moved substreams with the clock of the target service. Then in this case such functionality is useful.

Thank you very much! :wink:

**Pull request closed without merging**
