### PR TITLE
Handle "input-modulation" flag for DVB-T2 dektec output

### PR DESCRIPTION
**Pull request by macczy**
"--input-modulation" flag allowed to automatically calculate modulation
parameters when streaming with dektec output plugin from file using DVB-T modulation.
However, it was ignored for DVB-T2. Therefore handle it in a similar manner for DVB-T2.

#### Affected components:
dektec output plugin

#### Brief description of the proposed changes:
Recently I've asked about related problems here: https://github.com/tsduck/tsduck/issues/961
I was advised to use additional stuffing, and that worked for a while, but, in afterthought, didn't seem like long term solution. Then I discovered, that I have similar issues when streaming in DVB-T. But those could be easily solved with "input-modulation" flag. Therefore I would like to add support for this flag for DVB-T2 as well.

### CODE REVIEW

**Comment by lelegard** [comment]
Thanks @macczy.
I will review this. In the meantime, please replace my name with your full name in new source files you create. You are the author, I am not.

**Comment by macczy** [comment]
Hi @lelegard,
I've updated the name in a new commit for now. I assume we can just squash them during merge if you accept my change.

**Comment by macczy** [comment]
Looking at CI errors, I had to move new files to the dektec-specific directory, so that's done.
There was also this:
`XXXX  1 tests FAILED, 1614 tests passed, review failed tests in /home/runner/work/tsduck/tsduck-test/tmp/.failed
make: *** [Makefile:77: test-suite] Error 1
==== tmp/test-019.tsp.output.dektec.linux.help.diff
195,196c195,196
<       Otherwise, if the specified modulation is DVB-T, try to guess some
<       modulation parameters from the bitrate.
---
>       Otherwise, if the specified modulation is DVB-T or DVB-T2, try to guess
>       some modulation parameters from the bitrate.
Error: Process completed with exit code 2.`
I had to change the help message a bit, so I assume that's something to update in CI? Or is there some testing file I couldn't find that holds the old help messages?

**Comment by lelegard** [comment]
> Or is there some testing file I couldn't find that holds the old help messages?

The test suite also checks the help text of all commands and plugins to detect potential breaks. When options are added or modified, the reference texts must be manually regenerated and checked. There is a procedure for that. I will handle that, don't worry about that "failure".

If you are interested in the way TSDuck is tested, you may have a look [here](https://tsduck.io/doxy/testing.html) and [here](https://github.com/tsduck/tsduck-test).

**Pull request merged**
