### PR TITLE
Add AVS3, VVC and EVC related descriptors

### PR DESCRIPTION
**Pull request by paulhiggs**

### CODE REVIEW

**Comment by lelegard** [comment]
Hi @paulhiggs 

Thanks a lot for the update with the new standards 👍

In the new source files, please put your name in the copyright lines instead of mine. You are the author, I am not. You own the copyright for these files.

You may also add your name at the end of the CONTRIBUTORS.txt file.

**Comment by lelegard** [comment]
You also need to update the tables XML model file in `src/libtsduck/config`.

The model file is used to validate input XML files. This is the way an invalid table or descriptor is detected ahead of the XML deserialization methods of the various classes. The principles of XML model files is explained in section 2.6.3 of the user's guide.

I agree that the XML model file is huge and not immediately detectable for implementors of new tables and descriptors. I plan to make it modular in the source tree so that each table or descriptor will have its `.xml` file along with its `.h` and `.cpp`.

**Comment by lelegard** [comment]
> finding a way to develop the model from the source would be useful and less prone to oversight.

Definitely. Ideally, I used to have a dream about a tool which could describe the binary using some formal representation (XML or other) and then automatically generate the XML model and the manipulation code (or allow dynamically handling of general structures from the formal description at run-time). 

However, such a tool would be a project in itself. If I had anticipated the amount of work for tables and descriptors 15 years ago, I would have started with such a tool. And when you realize that the tool would have been useful, it is too late, the amount of remaining work for the new descriptors or tables is much lower than developing the tool.

Would you have a real-world stream with all these new descriptors? I mean a stream which was generated by another tool, not TSDuck. I would add the stream (or at least the TS packets containing the tables) in the non-regression test suite?

Please let me know when you're done with the commits so that I can start the merge.

**Comment by paulhiggs** [comment]
I'm done with all the commits I need for now as part of the DVB Next Generation Video Codecs activity. Sorry there was so many, but the Ubuntu and macos builds throw errors that are not present on my local Win64 system.

**Comment by lelegard** [comment]
Hi @paulhiggs 

I am reviewing the code, fixing a few XML glitches and adding tests in the [test suite](https://github.com/tsduck/tsduck-test).

I do not have recent versions for the standard, they are not freely available. Could provide the syntax table for EVC_video_descriptor? There is some inconsistency I need to fix.

**Comment by lelegard** [comment]
@paulhiggs 

> Could provide the syntax table for EVC_video_descriptor? 

And also VVC_video_descriptor please.

**Comment by paulhiggs** [comment]
EVC_video_descriptor is table 2-140 in [H.222.0](https://www.itu.int/itu-t/recommendations/rec.aspx?rec=14658) which is freely available (ISO/IEC 13818-1 8th edition which has the same information is not free). 
VVC_video_descriptor is table 2-133 in same document.

from ISO/IEC 13818-1 8th edition...
evc_video_descriptor
vvc_video_descriptor

**Comment by lelegard** [comment]
Thanks @paulhiggs 

> EVC_video_descriptor is table 2-140 in [H.222.0](https://www.itu.int/itu-t/recommendations/rec.aspx?rec=14658) which is freely available (ISO/IEC 13818-1 8th edition which has the same information is not free).

It must be in the 2021 edition, which is not free, even in the H.222.0 version. The [H.222.0 (06/21) page](https://www.itu.int/rec/T-REC-H.222.0-202106-I) says _"This text was produced through a joint activity with ISO and IEC. According to the agreement with our partners, this document is only available through payment. Please get in touch with sales@itu.int for more information."_

This is quite logical and, to my experience, it has always been like that: the latest edition of H.222.0 is not freely available. I hate this ISO policy, it prevents open source developers from having access to the most up-to-date standards.

**Comment by lelegard** [comment]
Hi @paulhiggs 

I have some questions about the AVS3_video_descriptor. 

- What is the document "T/AI 109-6" you mention in the source code? Is this a Chinese AVS document or a DVB document?
- The descriptor tag is 0xD1. In DVB signalisation, this is in the private descriptor range but no private data specifier is defined. Is this descriptor valid in a DVB stream? Or is this an extension for AVS countries (ie. China)?
- How is AVS3 integrated in DVB streams?

Since you added `AVS` in the list of standards in `tsStandards.h`, I will assume that this is not DVB compliant and I will add an option `--avs` (just like `--atsc` or `--isdb`) in relevant tools and plugins to force the interpretation of AVS-specific signalisation. Do you agree?

**Comment by paulhiggs** [comment]
@lelegard

> * What is the document "T/AI 109-6" you mention in the source code? Is this a Chinese AVS document or a DVB document?
There are two principal documents associated with AVS3, both are developed by the AVS Working Group of China (note that AVS3 has now been included in the [DVB Bluebook A001 a.k.a. "the codec toolbox"](https://dvb.org/wp-content/uploads/2022/02/A001r20_Use-of-Video-and-Audio-Coding-in-Broadcast-and-Broadband-Applications_Draft_TS_101-154-v281_July-2022.pdf))
The AVS3 video coding specification (T/AI 109.2) and the AVS3 systems specification (T/AI 109.6 where the AVS3_video_descriptor is defined) are both freely available from [here](http://avs.org.cn/AVS3_download/en_index.asp).

> * The descriptor tag is 0xD1. In DVB signalisation, this is in the private descriptor range but no private data specifier is defined. Is this descriptor valid in a DVB stream? Or is this an extension for AVS countries (ie. China)?
Indeed, there is no formal way of registering  for values in the user private descriptor range and we do not find a registrar or registry for the private descriptor range of ITU-T H.222.0 / ISO/IEC 13818-1 we just had to take a value which we determined was not available. We did ask ATSC to record our use in the [ATSC Code Point Registry](https://www.atsc.org/documents/code-point-registry), but they declined.

In regard to the using the extended stream id, we consulted with SMPTE, the authors of Direc and other codecs but all indicated a 'free for all' in grabbing tag vales. In the end we followed the previous approach used by VC-1 (another non-MPEG codec) in an MPEG-2 transport stream and 'obtained' a value that was not identified in the [MediaInfo](https://github.com/MediaArea/MediaInfoLib/blob/master/Source/MediaInfo/Multiple/File_MpegPs.cpp#L149) code for the extended stream id.
 
> * How is AVS3 integrated in DVB streams?
According to clause 4 of [DVB Bluebook A001](https://dvb.org/wp-content/uploads/2022/02/A001r20_Use-of-Video-and-Audio-Coding-in-Broadcast-and-Broadband-Applications_Draft_TS_101-154-v281_July-2022.pdf).

> 
> Since you added `AVS` in the list of standards in `tsStandards.h`, I will assume that this is not DVB compliant and I will add an option `--avs` (just like `--atsc` or `--isdb`) in relevant tools and plugins to force the interpretation of AVS-specific signalisation. Do you agree?
I'm not sure what 'DVB compliant' means in tsduck. The new DVB codec toolbox includes AVS3 alongside VVC (H.266) and HEVC. Going forward, a perfectly valid DVB transport stream (or DVB-DASH streaming service) will include AVS3 coded media and related signalling.

**Comment by lelegard** [comment]
> I'm not sure what 'DVB compliant' means in tsduck. 

This is not specifically TSDuck, this is DVB. In DVB, descriptor tags 0x80 to 0xFF are "private", they cannot be used by DVB. They are typically used by countries or operators. Private descriptors _must_ be preceded by a private_data_specifier_descriptor containing the private_data_specifier of the country or operator defining this private descriptor.

This means that it is forbidden to use 0xD1 as descriptor tag in a DVB transport stream, unless you are a private entity with a DVB-registered private_data_specifier  and you precede your 0xD1 descriptor with a private_data_specifier_descriptor containing your private_data_specifier.

This is DVB. SMPTE is a different standard body, they are not DVB. If they let you use 0xD1 (and even register it in SMPTE), your TS will be SMPTE-compliant, but not DVB-compliant.

We had a similar issue with AC-3. ATSC (which is not DVB either) decided to use 0x81 for an AC3 descriptor. For the same reasons, this value is invalid in DVB. Consequently, DVB defined another form of AC3 descriptor with tag 0x6A, officially registered in EN 300 468 (and a different structure).

So, if you describe your AVS3 elementary stream with a 0xD1 descriptor in SMPTE transport streams, you cannot do that in DVB transport stream. You need to apply for a specific descriptor at ETSI. Since the range 0x40-0x7F is already saturated, you will get an "extended descriptor", meaning that you will have to define a slightly different structure.

And you will necessary end up with the same situation as AC3: two different AVS3 descriptors for SMPTE and DVB, with different tags and slightly different structures.

**Comment by paulhiggs** [comment]
OK, thanks. I will raise the use of private_data_specifier with DVB and AVS. It should not be a problem to get the necessary identifiers.


________________________________

**Comment by lelegard** [comment]
Hi @paulhiggs 

I have integrated your code. The PR is not automatically marked as merged by GitHub because I skipped the last 3 commits which were integrations and reverts of the bug fix in c46290484cdf45fa4ae0d4509b3c732c137276b1. They were not needed since merging with the master branch brings that commit back. So, you may close the PR if you like and reopen one or an issue when a DVB AVS3 descriptor is defined.

I have added test-115 in the [test-suite](https://github.com/tsduck/tsduck-test) for your 8 new descriptors. This kind of test is predefined: just create an XML file with several examples of the new tables or descriptors. No matter the semantics, this is just a way to test the syntax, all possible conversions follow between XML, JSON, binary section, TS packets in both directions. The first time, it helps to find bugs (I fixed a few in these descriptors). Then, all intermediate results are kept in the test suite to track potential direct or induced regression in the future.

I also removed a few extra fields in the XML. For instance, when a binary structure contains a field to indicate the number of following subprofile IDC, this is useful in binary (how many bytes to decode) but useless in XML (just count the XML substructures). As a general method, when looking at a new binary descriptor, we need to classify semantic fields and syntactic fields apart. Only the semantic fields need to be transposed in XML. The XML format carries its own syntax.

Thanks again for this very useful contribution. Since you seem deeply involved with the integration of new codecs, we are lucky to have your direct contribution. If TSDuck can help in the prototyping and testing of these new codecs, I will consider this as an achievement.

**Comment by paulhiggs** [comment]
Thanks @lelegard for easing this process along. I will look more at the test suite to see how it can be enhanced.

It is likely we still need [````07146c0````](https://github.com/tsduck/tsduck/pull/1063/commits/07146c0ef7700d3dc3f72cfb7d20f4abb027d5a4) since the VVC Timing and HRD descriptor uses the same logic (negative flag for 90kHz) as HEVC and I 'copied' the HEVC code to get things started.
VVC_timing_and_HDR_descriptor()

**Comment by lelegard** [comment]
> It is likely we still need [07146c0](https://github.com/tsduck/tsduck/pull/1063/commits/07146c0ef7700d3dc3f72cfb7d20f4abb027d5a4) since the VVC Timing and HRD descriptor uses the same logic (negative flag for 90kHz) as HEVC and I 'copied' the HEVC code to get things started.

Ooops !!! My bad.

Because of the similarities between the two descriptors, I did not pay enough attention and incorrectly assumed it was the HEVC descriptor patch being integrated twice, back and forth. I merge this one right away.

**Review by Weerasak1239 — APPROVED** [review]
Ttt

**Pull request merged**
